### ISSUE TITLE
More of a question than an issue - can one filter

### ISSUE THREAD

**Issue by IanAdd** [djtimca/harocketlaunchlive#5]
You provide the next five launches.

Is this a limitation of the data made available or your prudent choice of a limit.

I would like it if I could filter to get SpaceX launches most of the time.

Ian

**Comment by djtimca** [comment]
I don't have a filter, but you could also install the SpaceX integration which gives you only next and latest SpaceX launches with significantly more detail.

**Comment by tango2590** [comment]
This would be a really nice addition to an already awesome integration. I already have the SpaceX one, but it's obviously only for SpaceX. For example, I could care less about the other countries unless it's a much anticipated launch, especially since streams for those are hit or miss. I'd love to be able to filter to just see US ones, such as ULA, Blue Origin, Rocket Lab, etc. Right now I have a very sketchy workaround using Node Red to filter the Provider attribute.

**Comment by djtimca** [comment]
Reopened as enhancement suggestion for next time I can get around to it.

**Comment by djtimca** [comment]
I've done another review on this and you can use the attributes already to filter alerts and for conditional cards to show / alert just the ones you are most interested in. I'm not likely to come back to add any filtering logic at the integration level.
